apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webapp-sandbox
namePrefix: sandbox-

resources:
  - ../../base
  - namespace.yaml

labels:
  - pairs:
      environment: sandbox
    includeSelectors: false
    includeTemplates: true
