apiVersion: v1
kind: Pod
metadata:
  name: sa-demo
  namespace: dso202-assignment-01
  labels:
    app: sa-demo
spec:
  serviceAccountName: cluster-viewer
  containers:
    - name: sa-demo
      image: sarojsanyasi/dso202-frontend:1.0
      command: ["sleep", "3600"]
