apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: dso202-assignment-01
type: Opaque
stringData:
  DB_USER: "taskuser"
  DB_PASSWORD: "changeme123"
  POSTGRES_USER: "taskuser"
  POSTGRES_PASSWORD: "changeme123"
